import type { TourPackage } from "@/lib/types";

/** Mock tour packages only (10 packages). All other data is empty in the app. */
export const mockPackages: TourPackage[] = [
  {
    id: "p1",
    name: "Ceylon Heritage & Wildlife",
    duration: "8 Days / 7 Nights",
    destination: "Sri Lanka",
    region: "Cultural Triangle",
    imageUrl: "https://images.unsplash.com/photo-1588668803695-82674663b423?w=800",
    price: 1890,
    rating: 4.9,
    reviewCount: 127,
    featured: true,
    published: true,
    cancellationPolicy: "Free cancellation up to 24 hours before",
    currency: "USD",
    description: "Experience the best of Sri Lanka: ancient cities, tea country, and wildlife safaris.",
    itinerary: [
      { day: 1, title: "Arrival - Colombo", description: "Airport pickup, transfer to Negombo.", accommodation: "Jetwing Lagoon" },
      { day: 2, title: "Sigiriya & Dambulla", description: "Lion Rock fortress, cave temples.", accommodation: "Heritance Kandalama" },
      { day: 3, title: "Sigiriya to Kandy", description: "Temple of the Tooth, cultural show.", accommodation: "Cinnamon Citadel" },
      { day: 4, title: "Tea Country", description: "Nuwara Eliya, tea factory tour.", accommodation: "Heritance Tea Factory" },
      { day: 5, title: "Yala Safari", description: "Full day safari in Yala National Park.", accommodation: "Cinnamon Wild" },
      { day: 6, title: "Galle Coast", description: "Galle Fort, beach time.", accommodation: "Fort Bazaar" },
      { day: 7, title: "Southern Coast", description: "Free day, optional activities.", accommodation: "Fort Bazaar" },
      { day: 8, title: "Departure", description: "Transfer to Colombo airport." },
    ],
    inclusions: ["All accommodation", "Meals as specified", "Private vehicle", "Safari jeep", "Entrance fees"],
    exclusions: ["International flights", "Travel insurance", "Personal expenses"],
    accommodationOptions: [
      { id: "acc1", label: "Jetwing Lagoon", price: 120, priceType: "per_night", supplierId: "h1", isDefault: true },
      { id: "acc2", label: "Heritance Kandalama", price: 185, priceType: "per_night", supplierId: "h2" },
      { id: "acc3", label: "Fort Bazaar", price: 95, priceType: "per_night", supplierId: "h3" },
    ],
    transportOptions: [
      { id: "tr1", label: "Private Car & Driver", price: 80, priceType: "per_day", supplierId: "ht1", isDefault: true },
      { id: "tr2", label: "Premium Van", price: 120, priceType: "per_day" },
      { id: "tr3", label: "Luxury Coach", price: 50, priceType: "per_person" },
    ],
    mealOptions: [
      { id: "m1", label: "BB (Breakfast)", price: 0, priceType: "total", isDefault: true },
      { id: "m2", label: "HB (Half Board)", price: 25, priceType: "per_person" },
      { id: "m3", label: "FB (Full Board)", price: 45, priceType: "per_person" },
      { id: "m4", label: "AI (All Inclusive)", price: 75, priceType: "per_person" },
    ],
    createdAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "p2",
    name: "Beach & Culture Escape",
    duration: "5 Days / 4 Nights",
    destination: "Sri Lanka",
    region: "Southern Coast",
    imageUrl: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800",
    price: 690,
    rating: 4.7,
    reviewCount: 89,
    featured: true,
    published: true,
    cancellationPolicy: "Free cancellation up to 24 hours before",
    currency: "USD",
    description: "A relaxing blend of Galle heritage and Unawatuna beach.",
    itinerary: [
      { day: 1, title: "Arrival - Galle", description: "Transfer from airport, explore Galle Fort.", accommodation: "Fort Bazaar" },
      { day: 2, title: "Galle Fort", description: "Walking tour, lighthouse, boutiques.", accommodation: "Fort Bazaar" },
      { day: 3, title: "Unawatuna Beach", description: "Beach day, optional snorkeling.", accommodation: "Fort Bazaar" },
      { day: 4, title: "Free Day", description: "Spa, cooking class, or relaxation.", accommodation: "Fort Bazaar" },
      { day: 5, title: "Departure", description: "Transfer to airport." },
    ],
    inclusions: ["Accommodation", "Breakfast", "Airport transfers", "Fort walk"],
    exclusions: ["Lunch & dinner", "International flights", "Activities"],
    accommodationOptions: [
      { id: "acc4", label: "Fort Bazaar", price: 95, priceType: "per_night", supplierId: "h3", isDefault: true },
    ],
    transportOptions: [
      { id: "tr4", label: "Private Car & Driver", price: 60, priceType: "per_day", supplierId: "ht1", isDefault: true },
    ],
    mealOptions: [
      { id: "m5", label: "BB (Breakfast)", price: 0, priceType: "total", isDefault: true },
      { id: "m6", label: "HB (Half Board)", price: 20, priceType: "per_person" },
    ],
    createdAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "p3",
    name: "Tea Country & Hill Country",
    duration: "4 Days / 3 Nights",
    destination: "Sri Lanka",
    region: "Tea Country",
    imageUrl: "https://images.unsplash.com/photo-1569827156433-daf971e7d91a?w=800",
    price: 420,
    rating: 4.8,
    reviewCount: 56,
    featured: false,
    published: true,
    cancellationPolicy: "Free cancellation up to 48 hours before",
    currency: "USD",
    description: "Scenic train rides, tea plantations, and cool mountain air.",
    itinerary: [
      { day: 1, title: "Kandy to Ella", description: "Scenic train journey through tea country.", accommodation: "98 Acres" },
      { day: 2, title: "Ella Exploration", description: "Little Adam's Peak, Nine Arch Bridge.", accommodation: "98 Acres" },
      { day: 3, title: "Nuwara Eliya", description: "Tea factory, Gregory Lake.", accommodation: "Heritance Tea Factory" },
      { day: 4, title: "Departure", description: "Transfer to Colombo or airport." },
    ],
    inclusions: ["Accommodation", "Breakfast", "Train tickets", "Tea factory tour"],
    exclusions: ["Lunch & dinner", "Flights"],
    accommodationOptions: [
      { id: "acc5", label: "98 Acres", price: 150, priceType: "per_night", supplierId: "h4", isDefault: true },
      { id: "acc6", label: "Heritance Tea Factory", price: 200, priceType: "per_night", supplierId: "h5" },
    ],
    transportOptions: [
      { id: "tr5", label: "Private Car & Driver", price: 70, priceType: "per_day", supplierId: "ht1", isDefault: true },
      { id: "tr6", label: "Premium Van", price: 90, priceType: "per_day", supplierId: "ht2" },
    ],
    mealOptions: [
      { id: "m7", label: "BB (Breakfast)", price: 0, priceType: "total", isDefault: true },
      { id: "m8", label: "HB (Half Board)", price: 22, priceType: "per_person" },
    ],
    createdAt: "2026-01-20T00:00:00Z",
  },
  {
    id: "p4",
    name: "Wildlife Safari Adventure",
    duration: "3 Days / 2 Nights",
    destination: "Sri Lanka",
    region: "Yala",
    imageUrl: "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800",
    price: 550,
    rating: 4.6,
    reviewCount: 43,
    featured: true,
    published: true,
    cancellationPolicy: "Free cancellation up to 24 hours before",
    currency: "USD",
    description: "Yala National Park safari and beach relaxation.",
    itinerary: [
      { day: 1, title: "Arrival - Yala", description: "Transfer to safari lodge.", accommodation: "Cinnamon Wild" },
      { day: 2, title: "Full Day Safari", description: "Yala National Park wildlife safari.", accommodation: "Cinnamon Wild" },
      { day: 3, title: "Departure", description: "Beach stop, transfer to airport." },
    ],
    inclusions: ["Accommodation", "Meals", "Safari jeep", "Park fees"],
    exclusions: ["Flights", "Tips"],
    accommodationOptions: [
      { id: "acc7", label: "Cinnamon Wild", price: 220, priceType: "per_night", supplierId: "h6", isDefault: true },
      { id: "acc8", label: "Jetwing Yala", price: 180, priceType: "per_night", supplierId: "h7" },
    ],
    transportOptions: [
      { id: "tr7", label: "Safari Jeep", price: 100, priceType: "per_day", supplierId: "ht4", isDefault: true },
      { id: "tr8", label: "Private Car & Driver", price: 75, priceType: "per_day", supplierId: "ht1" },
    ],
    mealOptions: [
      { id: "m9", label: "FB (Full Board)", price: 40, priceType: "per_person", isDefault: true },
      { id: "m10", label: "AI (All Inclusive)", price: 65, priceType: "per_person" },
    ],
    createdAt: "2026-01-22T00:00:00Z",
  },
  {
    id: "p5",
    name: "Colombo City & Coast",
    duration: "2 Days / 1 Night",
    destination: "Sri Lanka",
    region: "Colombo",
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    price: 180,
    rating: 4.5,
    reviewCount: 31,
    featured: false,
    published: true,
    cancellationPolicy: "Free cancellation up to 12 hours before",
    currency: "USD",
    description: "Quick city tour, temples, and beachside dinner.",
    itinerary: [
      { day: 1, title: "Colombo Tour", description: "Gangaramaya Temple, markets, Galle Face.", accommodation: "Shangri-La Colombo" },
      { day: 2, title: "Departure", description: "Airport transfer." },
    ],
    inclusions: ["Accommodation", "Breakfast", "City tour", "Airport transfer"],
    exclusions: ["Lunch & dinner", "Shopping"],
    accommodationOptions: [
      { id: "acc9", label: "Shangri-La Colombo", price: 250, priceType: "per_night", supplierId: "h8", isDefault: true },
      { id: "acc10", label: "Jetwing Lagoon", price: 120, priceType: "per_night", supplierId: "h1" },
    ],
    transportOptions: [
      { id: "tr9", label: "Private Car & Driver", price: 60, priceType: "per_day", supplierId: "ht1", isDefault: true },
      { id: "tr10", label: "Luxury Coach", price: 30, priceType: "per_person", supplierId: "ht3" },
    ],
    mealOptions: [
      { id: "m11", label: "BB (Breakfast)", price: 0, priceType: "total", isDefault: true },
      { id: "m12", label: "HB (Half Board)", price: 35, priceType: "per_person" },
    ],
    createdAt: "2026-01-25T00:00:00Z",
  },
  {
    id: "p6",
    name: "Extended Heritage Journey",
    duration: "10 Days / 9 Nights",
    destination: "Sri Lanka",
    region: "Cultural Triangle",
    imageUrl: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800",
    price: 2490,
    rating: 4.9,
    reviewCount: 72,
    featured: true,
    published: true,
    cancellationPolicy: "Free cancellation up to 72 hours before",
    currency: "USD",
    description: "Comprehensive tour from Sigiriya to Galle—temples, tea, wildlife, and coast.",
    itinerary: [
      { day: 1, title: "Arrival - Negombo", description: "Airport pickup, beach relaxation.", accommodation: "Jetwing Lagoon" },
      { day: 2, title: "Sigiriya Rock", description: "Lion Rock fortress, Dambulla caves.", accommodation: "Heritance Kandalama" },
      { day: 3, title: "Polonnaruwa", description: "Ancient royal capital.", accommodation: "Heritance Kandalama" },
      { day: 4, title: "Kandy", description: "Temple of the Tooth, cultural show.", accommodation: "Cinnamon Citadel" },
      { day: 5, title: "Train to Ella", description: "Scenic rail through tea country.", accommodation: "98 Acres" },
      { day: 6, title: "Ella Highlights", description: "Nine Arch Bridge, Little Adam's Peak.", accommodation: "98 Acres" },
      { day: 7, title: "Yala Safari", description: "Leopards and wildlife.", accommodation: "Cinnamon Wild" },
      { day: 8, title: "Galle Fort", description: "Colonial heritage, lighthouse.", accommodation: "Fort Bazaar" },
      { day: 9, title: "Southern Coast", description: "Beach day, optional diving.", accommodation: "Fort Bazaar" },
      { day: 10, title: "Departure", description: "Transfer to airport." },
    ],
    inclusions: ["All accommodation", "Meals as specified", "Private vehicle", "Train tickets", "Safari jeep", "Entrance fees"],
    exclusions: ["International flights", "Travel insurance", "Personal expenses"],
    accommodationOptions: [
      { id: "acc11", label: "Jetwing Lagoon", price: 120, priceType: "per_night", supplierId: "h1", isDefault: true },
      { id: "acc12", label: "Heritance Kandalama", price: 185, priceType: "per_night", supplierId: "h2" },
      { id: "acc13", label: "Fort Bazaar", price: 95, priceType: "per_night", supplierId: "h3" },
    ],
    transportOptions: [
      { id: "tr11", label: "Private Car & Driver", price: 85, priceType: "per_day", supplierId: "ht1", isDefault: true },
      { id: "tr12", label: "Premium Van", price: 120, priceType: "per_day", supplierId: "ht2" },
    ],
    mealOptions: [
      { id: "m13", label: "BB (Breakfast)", price: 0, priceType: "total", supplierId: "hm1", isDefault: true },
      { id: "m14", label: "HB (Half Board)", price: 28, priceType: "per_person", supplierId: "hm2" },
      { id: "m15", label: "FB (Full Board)", price: 48, priceType: "per_person", supplierId: "hm3" },
    ],
    createdAt: "2026-01-28T00:00:00Z",
  },
  {
    id: "p7",
    name: "Whale Watching & South Coast",
    duration: "5 Days / 4 Nights",
    destination: "Sri Lanka",
    region: "Southern Coast",
    imageUrl: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=800",
    price: 890,
    rating: 4.7,
    reviewCount: 58,
    featured: true,
    published: true,
    cancellationPolicy: "Free cancellation up to 24 hours before",
    currency: "USD",
    description: "Blue whales off Mirissa and the charms of Galle and Unawatuna.",
    itinerary: [
      { day: 1, title: "Arrival - Galle", description: "Transfer, Galle Fort walk.", accommodation: "Fort Bazaar" },
      { day: 2, title: "Whale Watching", description: "Mirissa whale watching excursion.", accommodation: "Fort Bazaar" },
      { day: 3, title: "Unawatuna Beach", description: "Beach day, snorkeling.", accommodation: "Fort Bazaar" },
      { day: 4, title: "Free Day", description: "Spa, cooking class, or diving.", accommodation: "Fort Bazaar" },
      { day: 5, title: "Departure", description: "Transfer to airport." },
    ],
    inclusions: ["Accommodation", "Breakfast", "Whale watching tour", "Airport transfers"],
    exclusions: ["Lunch & dinner", "International flights", "Diving"],
    accommodationOptions: [
      { id: "acc14", label: "Fort Bazaar", price: 95, priceType: "per_night", supplierId: "h3", isDefault: true },
    ],
    transportOptions: [
      { id: "tr13", label: "Private Car & Driver", price: 65, priceType: "per_day", supplierId: "ht1", isDefault: true },
      { id: "tr14", label: "Minivan", price: 55, priceType: "per_day", supplierId: "ht5" },
    ],
    mealOptions: [
      { id: "m16", label: "BB (Breakfast)", price: 0, priceType: "total", supplierId: "hm1", isDefault: true },
      { id: "m17", label: "HB (Half Board)", price: 22, priceType: "per_person", supplierId: "hm2" },
    ],
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "p8",
    name: "Luxury Wellness Retreat",
    duration: "4 Days / 3 Nights",
    destination: "Sri Lanka",
    region: "Tea Country",
    imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800",
    price: 1290,
    rating: 4.9,
    reviewCount: 34,
    featured: false,
    published: true,
    cancellationPolicy: "Free cancellation up to 48 hours before",
    currency: "USD",
    description: "Yoga, spa, and mountain serenity at a boutique tea estate hotel.",
    itinerary: [
      { day: 1, title: "Arrival - Nuwara Eliya", description: "Transfer, welcome massage.", accommodation: "Heritance Tea Factory" },
      { day: 2, title: "Yoga & Nature", description: "Morning yoga, tea plantation walk.", accommodation: "Heritance Tea Factory" },
      { day: 3, title: "Spa Day", description: "Full day wellness treatments.", accommodation: "Heritance Tea Factory" },
      { day: 4, title: "Departure", description: "Transfer to Colombo or airport." },
    ],
    inclusions: ["Luxury accommodation", "All meals", "Yoga sessions", "Spa treatments", "Private transfers"],
    exclusions: ["Flights"],
    accommodationOptions: [
      { id: "acc15", label: "Heritance Tea Factory", price: 200, priceType: "per_night", supplierId: "h5", isDefault: true },
      { id: "acc16", label: "98 Acres", price: 150, priceType: "per_night", supplierId: "h4" },
    ],
    transportOptions: [
      { id: "tr15", label: "Private Car & Driver", price: 75, priceType: "per_day", supplierId: "ht1", isDefault: true },
    ],
    mealOptions: [
      { id: "m18", label: "FB (Full Board)", price: 55, priceType: "per_person", supplierId: "hm3", isDefault: true },
      { id: "m19", label: "AI (All Inclusive)", price: 85, priceType: "per_person", supplierId: "hm4" },
    ],
    createdAt: "2026-02-05T00:00:00Z",
  },
  {
    id: "p9",
    name: "Sigiriya Express",
    duration: "2 Days / 1 Night",
    destination: "Sri Lanka",
    region: "Cultural Triangle",
    imageUrl: "https://images.unsplash.com/photo-1569864358643-6b2ead2d2c46?w=800",
    price: 320,
    rating: 4.6,
    reviewCount: 41,
    featured: false,
    published: true,
    cancellationPolicy: "Free cancellation up to 12 hours before",
    currency: "USD",
    description: "Quick trip to climb Lion Rock and explore Dambulla caves.",
    itinerary: [
      { day: 1, title: "Sigiriya & Dambulla", description: "Lion Rock fortress, cave temples.", accommodation: "Heritance Kandalama" },
      { day: 2, title: "Departure", description: "Return to Colombo or airport." },
    ],
    inclusions: ["Accommodation", "Breakfast", "Entrance fees", "Private vehicle"],
    exclusions: ["Lunch & dinner", "Flights"],
    accommodationOptions: [
      { id: "acc17", label: "Heritance Kandalama", price: 185, priceType: "per_night", supplierId: "h2", isDefault: true },
      { id: "acc18", label: "Jetwing Lagoon", price: 120, priceType: "per_night", supplierId: "h1" },
    ],
    transportOptions: [
      { id: "tr16", label: "Private Car & Driver", price: 80, priceType: "per_day", supplierId: "ht1", isDefault: true },
    ],
    mealOptions: [
      { id: "m20", label: "BB (Breakfast)", price: 0, priceType: "total", supplierId: "hm1", isDefault: true },
    ],
    createdAt: "2026-02-08T00:00:00Z",
  },
  {
    id: "p10",
    name: "East Coast Beaches",
    duration: "5 Days / 4 Nights",
    destination: "Sri Lanka",
    region: "Eastern Province",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    price: 620,
    rating: 4.5,
    reviewCount: 27,
    featured: false,
    published: true,
    cancellationPolicy: "Free cancellation up to 24 hours before",
    currency: "USD",
    description: "Pristine beaches, surfing, and laid-back coastal life.",
    itinerary: [
      { day: 1, title: "Arrival - Trincomalee", description: "Transfer, beach check-in.", accommodation: "Jetwing Lagoon" },
      { day: 2, title: "Pigeon Island", description: "Snorkeling, coral reef.", accommodation: "Jetwing Lagoon" },
      { day: 3, title: "Surf & Sun", description: "Surf lessons or relaxation.", accommodation: "Jetwing Lagoon" },
      { day: 4, title: "Whale & Dolphin", description: "Optional whale watching.", accommodation: "Jetwing Lagoon" },
      { day: 5, title: "Departure", description: "Transfer to airport." },
    ],
    inclusions: ["Accommodation", "Breakfast", "Pigeon Island boat", "Transfers"],
    exclusions: ["Lunch & dinner", "Flights", "Surf lessons"],
    accommodationOptions: [
      { id: "acc19", label: "Jetwing Lagoon", price: 120, priceType: "per_night", supplierId: "h1", isDefault: true },
      { id: "acc20", label: "Fort Bazaar", price: 95, priceType: "per_night", supplierId: "h3" },
    ],
    transportOptions: [
      { id: "tr17", label: "Private Car & Driver", price: 70, priceType: "per_day", supplierId: "ht1", isDefault: true },
      { id: "tr18", label: "Minivan", price: 55, priceType: "per_day", supplierId: "ht5" },
    ],
    mealOptions: [
      { id: "m21", label: "BB (Breakfast)", price: 0, priceType: "total", supplierId: "hm1", isDefault: true },
      { id: "m22", label: "HB (Half Board)", price: 20, priceType: "per_person", supplierId: "hm2" },
    ],
    createdAt: "2026-02-10T00:00:00Z",
  },
];
